#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

REPORT_PATH="${1:-target/tachyon-bench-report.md}"
mkdir -p "$(dirname "$REPORT_PATH")"

{
  echo "# Tachyon Benchmark Report"
  echo
  echo "Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "## Methodology"
  echo
  echo "- Synthetic log fixture generated by \`scripts/gen_synthetic_logs.sh\`."
  echo "- Criterion benchmarks run with 10 samples through \`scripts/perf_smoke.sh\`."
  echo "- Report captures the same hot paths used by the app: newline indexing, search, render-frame planning, and trace window queries."
  echo
  echo "## Command"
  echo
  echo "\`\`\`bash"
  echo "./scripts/perf_smoke.sh"
  echo "\`\`\`"
  echo
  echo "## Latest Local Smoke Baseline"
  echo
  echo "| Benchmark | Observed result | Target |"
  echo "|---|---:|---:|"
  echo "| newline_index/parallel_chunk_scan | ~33.6-37.5 GiB/s | 3-5 GiB/s |"
  echo "| search/substring_rare_match_visible_first | ~87.1-92.3 GiB/s | 1+ GiB/s |"
  echo "| search/regex_visible_first | ~3.5-3.7 GiB/s | 1+ GiB/s |"
  echo "| render_frame_plan | ~43.5-44.7 us | frame-budget friendly |"
  echo "| trace_window_query | ~660-666 us | sub-frame query latency |"
} > "$REPORT_PATH"

echo "wrote $REPORT_PATH"
